services:
  audit-qcm-db:
    image: postgres:15
    container_name: qcm_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./apis/.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "qcm"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 30s
    networks:
      - qcm_network

  audit-qcm-apis:
    build:
      context: ./apis
      dockerfile: Dockerfile
    image: qcm-apis:latest
    container_name: qcm_apis
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      audit-qcm-db:
        condition: service_healthy
    env_file:
      - ./apis/.env
    networks:
      - qcm_network
    command: ["node", "./bin/server.js"]
    #command: ["sh", "-c", "node ace migration:run && node ace serve --watch"]

  audit-qcm-apps:
    build:
      context: ./apps
      dockerfile: Dockerfile
    container_name: audit_qcm_apps
    image: qcm-apps:latest
    restart: always
    ports:
      - "5173:80" # Nginx sert l'app sur le port 80, mappé sur 5174 en local
    networks:
      - qcm_network
    depends_on:
      - audit-qcm-apis

volumes:
  pg_data:

networks:
  qcm_network:
    driver: bridge
