
services:

  audit-qcm-db:
    image: postgres:15
    container_name: qcm_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - qcm_network


  audit-qcm-apis:
    build: ./apis
    container_name: qcm_apis
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - audit-qcm-db
    env_file:
      - ./apis/.env
    networks:
      - qcm_network
    command: ["node", "run", "dev"]

  frontend:
    build: ./apps
    container_name: qcm_apps
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - audit-qcm-apis
    networks:
      - qcm_network
    command: ["node", "run", "dev"]


volumes:
  pg_data:

networks:
  qcm_network:
    driver: bridge
